os: Visual Studio 2017

environment:
  global:
    BITS: 32
  matrix:
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: i686

build:
  project: ponyprog.pro
  parallel: true
  verbosity: detailed

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

install:
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/picusb/libftdi1-1.4git_devkit_x86_x64_14June2018.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpicusb%2Ffiles%2Flibftdi1-1.4git_devkit_x86_x64_14June2018.zip%2Fdownload&ts=1610734013" -FileName "C:\libftdi1-1.4git_devkit_x86_x64_14June2018.zip"
  - 7z x -y "C:\libftdi1-1.4git_devkit_x86_x64_14June2018.zip" -o"C:\"
  - if [%PLATFORM%]==[x86_64] set BITS=64
  - if [%PLATFORM%]==[x86_64] set EXTRA_OPTS=--disable-32bit
  - set QTDIR=C:\Qt\5.9.9\mingw53_32
  - set "INNOPATH=C:\Program Files (x86)\Inno Setup 5"
  - set "PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;%INNOPATH%"

build_script:
  - echo %PATH%
  - dir "%INNOPATH%"
  - dir "C:\libftdi1-1.4git_devkit_x86_x64_14June2018"
  - dir "C:\Libraries\boost_1_67_0"
  - cmake -E make_directory build
  - cd build && cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="c++" -DCMAKE_MAKE_PROGRAM="mingw32-make" -DUSE_DEBUGGER=OFF -DUSE_QT5=ON -DCMAKE_PREFIX_PATH="C:/libftdi1-1.4git_devkit_x86_x64_14June2018" -DLIBUSB_SKIP_VERSION_CHECK=ON ..
  - cd .. && qmake ponyprog.pro -spec win32-g++ BOOSTPATH=C:/Libraries/boost_1_67_0 FTDIPATH=C:/libftdi1-1.4git_devkit_x86_x64_14June2018
  - mingw32-make -j2
  - mingw32-make win32setup
  - type ponyprog.bat
  - ponyprog.bat

after_build:
  - 7z a ponyprog.zip distribution/innosetup/Output/PonyProg*.exe

artifacts:
  - path: ponyprog.zip
    name: Ponyprog
